spring.application.name=facturacion

spring.datasource.url=jdbc:mysql://localhost:3306/facturahp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Blackops4.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=9090
jwt.expiration=3600000
jwt.secret=miClaveSecretaMuySegura123
sri.firma.ruta=C:/Users/jair_/OneDrive/Documentos/firma/ELVIS JAIR SANDOVAL PORRAS 0704981703-210525095641.p12
sri.firma.clave=Jair2024